//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ql_Phongtro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnhPhong
    {
        public int HinhAnhID { get; set; }
        public int PhongID { get; set; }
        public string UrlHinhAnh { get; set; }
    
        public virtual PhongTro PhongTro { get; set; }
    }
}
