//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ql_Phongtro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichHen
    {
        public int LichHenID { get; set; }
        public int SinhVienID { get; set; }
        public int PhongID { get; set; }
        public System.DateTime ThoiGianHen { get; set; }
        public string GhiChu { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual PhongTro PhongTro { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
