//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ql_Phongtro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongTro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongTro()
        {
            this.HinhAnhPhong = new HashSet<HinhAnhPhong>();
            this.LichHen = new HashSet<LichHen>();
            this.TienIch = new HashSet<TienIch>();
        }
    
        public int PhongID { get; set; }
        public int ChuTroID { get; set; }
        public string TieuDe { get; set; }
        public string LoaiHinh { get; set; }
        public decimal GiaThue { get; set; }
        public Nullable<decimal> TienCoc { get; set; }
        public Nullable<decimal> TienDien { get; set; }
        public Nullable<decimal> TienNuoc { get; set; }
        public Nullable<decimal> PhiDichVu { get; set; }
        public int PhuongXaID { get; set; }
        public int TuyenDuongID { get; set; }
        public string DiaChiChiTiet { get; set; }
        public double DienTich { get; set; }
        public int SucChua { get; set; }
        public string TrangThaiPhong { get; set; }
        public string TrangThaiDuyet { get; set; }
        public string ThoiGianLienHe { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnhPhong> HinhAnhPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichHen> LichHen { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual PhuongXa PhuongXa { get; set; }
        public virtual TuyenDuong TuyenDuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TienIch> TienIch { get; set; }
    }
}
