//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ql_Phongtro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_PhongTroCaMauEntities : DbContext
    {
        public QL_PhongTroCaMauEntities()
            : base("name=QL_PhongTroCaMauEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HinhAnhPhong> HinhAnhPhong { get; set; }
        public virtual DbSet<LichHen> LichHen { get; set; }
        public virtual DbSet<NguoiDung> NguoiDung { get; set; }
        public virtual DbSet<PhongTro> PhongTro { get; set; }
        public virtual DbSet<PhuongXa> PhuongXa { get; set; }
        public virtual DbSet<TienIch> TienIch { get; set; }
        public virtual DbSet<TuyenDuong> TuyenDuong { get; set; }
    }
}
